ci: add workflow code-quality
autodocdev/sdk-plataforma-nodejs pull request #3
Opened 2023-01-31 18:41 UTC by diegorondao

2023-01-31 21:17 UTC, dcorrea777 requested changes

2023-01-31 21:17 UTC, dcorrea777 commented on .github/workflows/code-quality.yml
> +                run: npm install
Esse npm install faz a instalação tudo do zero, ou ele pega o cache que foi gerado no Job anterior ?

2023-02-01 11:24 UTC, diegorondao commented on .github/workflows/code-quality.yml
> +                run: npm install
Nesse caso ele não pega do cache. 
Acha legal criamos um step para pegar do cache ?

2023-02-01 14:42 UTC, dcorrea777 approved these changes

2023-02-01 14:42 UTC, merged